import type {Metadata} from "next";
import {Roboto} from 'next/font/google'
import "./globals.css";
import {ThemeProvider} from "@/components/providers/theme-provider";
import {ToasterProvider} from "@/components/providers/toaster-provider";

const roboto = Roboto({
    weight: ['100', '300', '400', '500', '700', '900'],
    style: ['normal', 'italic'],
    subsets: ['latin', 'cyrillic'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${roboto.className} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
            themes={['light', 'dark']}
        >
            <ToasterProvider/>
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
